version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Data/Dockerfile
    environment: 
      - MSSQL_SA_PASSWORD=Dexcelence!1
    networks:
      mssql-network:
        ipv4_address: 172.16.238.2

  identity:
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile.dev
    depends_on:
      - db
    environment: 
      - ConnectionStrings__DefaultConnection=Server=172.16.238.2;Database=identity;User=sa;Password=Dexcelence!1;
      - App__Self__IssuerUri=https://172.16.238.3:5004
      - App__Api__DeXApiUrl=https://172.16.238.4
      - ASPNETCORE_URLS=https://+;
      - ASPNETCORE_HTTPS_PORT=5005
      - ASPNETCORE_Kestrel__Certificates__Default__Password=W64x4AD8dNj9kImdX3tayS
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/dex-identity.pfx
    networks: 
      mssql-network:
        ipv4_address: 172.16.238.3
    ports:
      - 5004:80
      - 5005:443
    
  api:
    build:
      context: .
      dockerfile: API/Dockerfile.dev
    depends_on:
      - db
    environment: 
      - ConnectionStrings__DefaultConnection=Server=172.16.238.2;Database=master;User=sa;Password=Dexcelence!1;
      - App__IdentityServer__IdentityUrl=https://172.16.238.3
      - ASPNETCORE_URLS=https://+;
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=xI90DrNea7M6UJFNDwip6t
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/dex-api.pfx
    networks:
      mssql-network:
        ipv4_address: 172.16.238.4
    ports:
      - 5000:80
      - 5001:443

networks:
  mssql-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24